version: "3.7"
services:

  zotflask:
    build: .
    hostname: zotflask
    container_name: zotflask
    restart: always
    volumes:
      - ../flask:/flask
    working_dir: /flask
    networks:
      - frontend
#    command: "sleep 3600"
    command: "flask run --reload --host=0.0.0.0"

  zotnginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/www/static
    depends_on:
      - zotflask
    links:
      - zotflask:flask

    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.routers.zotnginx.tls.certresolver=myresolver
      - traefik.http.routers.zotnginx.rule=Host(`zotprojet.nasjo.fr`)
    networks:
      - frontend

networks:
  frontend:
    external: true


