version: "3.7"
services:

  flask:
    build: .
    hostname: flask
    container_name: flask
    restart: always
    volumes:
      - ../flask:/flask
    working_dir: /flask
    networks:
      - frontend
#    command: "sleep 3600"
    command: "flask run --reload --host=0.0.0.0"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/www/static
    depends_on:
      - flask
    links:
      - flask:flask
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.zotprojet.rule=Host(`zotprojet.nasjo.fr`)
    networks:
      - frontend

networks:
  frontend:
    external: true


